# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_created_at2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at2',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='', help_text='여기에 내용을 입력!!', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', help_text='여기에 제목을 입력!!', max_length=100),
            preserve_default=False,
        ),
    ]
